<?xml version="0.1"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="1 DoF Bot">

    <xacro:macro name="bot_description">
        <material name="red">
            <color rgba="1 0 0 1" />
        </material>

        <material name="blue">
            <color rgba="0 0 1 1" />
        </material>

        <material name="green">
            <color rgba="0 1 0 1" />
        </material>

        <link name="world" />
        <xacro:property name="base_width" value="0.1" />
        <xacro:property name="base_length" value="0.1" />
        <xacro:property name="base_height" value="0.7" />

        <xacro:property name="upper_width" value="0.1" />
        <xacro:property name="upper_length" value="0.1" />
        <xacro:property name="upper_height" value="0.5" />

        <xacro:property name="inertiaTest" value="0.1" />

        <joint name="fixed_joint" type="fixed">
            <parent link="world" />
            <child link="base_link" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <material name="red" />
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="1"/>
                <inertia ixx="${inertiaTest}" ixy="0" ixz="0" iyy="${inertiaTest}" iyz = "0" izz="${inertiaTest}" />
            </inertial>
        </link>

        <joint name="dof_joint" type="continuous" >
            <parent link="base_link" />
            <child link="upper_link" />
            <origin xyz="0 ${base_width/2} ${base_height - 0.1}" />
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <link name="upper_link">
            <visual>
                <origin xyz="0 ${upper_width/2} ${upper_height/2} " rpy="0 0 0" />
                <geometry>
                    <box size="${upper_length} ${upper_width} ${upper_height}" />
                </geometry>
                <material name="blue" />
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="1"/>
                <inertia ixx="${inertiaTest}" ixy="0" ixz="0" iyy="${inertiaTest}" iyz = "0" izz="${inertiaTest}" />
            </inertial>
        </link>


    </xacro:macro>
</robot>
